services:
  xlsx-translate-backend:
    build:
      context: ./backend
    container_name: xlsx-translate-backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - TRANSFORMERS_CACHE=/app/cache
      - LLM_BASE_URL=http://192.168.1.1:1234/v1 # CHANGE THIS TO YOUR LM API URL
      - LLM_API_KEY=lm-studio # CHANGE THIS TO YOUR LM API KEY
      - LLM_MODEL = qwen2.5-7b-instruct-1m # CHANGE THIS TO YOUR MODEL OF CHOICE
    restart: unless-stopped
    networks:
      - xlsx-translate-network

  xlsx-translate-frontend:
    build:
      context: ./frontend
    container_name: xlsx-translate-frontend
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8501"
    depends_on:
      - xlsx-translate-backend
    environment:
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped
    networks:
      - xlsx-translate-network

networks:
  xlsx-translate-network:
    driver: bridge
