services:
  xlsx-translate-backend:
    build:
      context: ./backend
    container_name: xlsx-translate-backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - TRANSFORMERS_CACHE=/app/cache
    restart: unless-stopped
    networks:
      - xlsx-translate-network
  xlsx-translate-frontend:
    build:
      context: ./frontend
    container_name: xlsx-translate-frontend
    volumes:
      - ./data:/app/data
    ports:
      - "8501:8501"
    depends_on:
      - xlsx-translate-backend
    environment:
      - STREAMLIT_SERVER_PORT=8501
    restart: unless-stopped
    networks:
      - xlsx-translate-network

networks:
  xlsx-translate-network:
    driver: bridge
